MvcStokProject/Controllers/SatisController.cs
using MvcStokProject.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcStokProject.Controllers
{
    public class SatisController : Controller
    {
        Db_StokEntities db = new Db_StokEntities();
        public ActionResult Index()
        {
            var deger = db.TBL_SATIS.ToList();
            return View(deger);
        }

        [HttpGet]
        public ActionResult SatisEkle()
        {
            //Ürün Listesi
            List<SelectListItem> urun = (from x in db.TBL_URUN.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.AD,
                                              Value = x.ID.ToString()
                                          }).ToList();
            ViewBag.urunList = urun;

            //Personel Listesi
            List<SelectListItem> personel = (from x in db.TBL_PERSONEL.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.AD+" "+x.SOYAD,
                                              Value = x.ID.ToString()
                                          }).ToList();
            ViewBag.personelList = personel;

            //Müşteri Listesi
            List<SelectListItem> musteri = (from x in db.TBL_MUSTERI.Where(x=>x.DURUM==true).ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.AD+" "+x.SOYAD,
                                              Value = x.ID.ToString()
                                          }).ToList();
            ViewBag.musteriList = musteri;


            return View();
        }

        [HttpPost]
        public ActionResult SatisEkle(TBL_SATIS p)
        {
            var urun = db.TBL_URUN.Where(x => x.ID == p.TBL_URUN.ID).FirstOrDefault();
            var personel = db.TBL_PERSONEL.Where(x => x.ID == p.TBL_PERSONEL.ID).FirstOrDefault();
            var musteri = db.TBL_MUSTERI.Where(x => x.ID == p.TBL_MUSTERI.ID).FirstOrDefault();
            p.TBL_URUN = urun;
            p.TBL_PERSONEL = personel;
            p.TBL_MUSTERI = musteri;
            p.TARIH = DateTime.Parse(DateTime.Now.ToString("dddd, dd MMMM yyyy HH:mm:ss"));
            db.TBL_SATIS.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcStokProject/Views/Satis/Index.cshtml
@using MvcStokProject.Models.Entity
@model List<TBL_SATIS>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>

    .margintop {
        margin-bottom: 15px;
    }

</style>
<h2 style="text-align:center; margin-top:15px;">Satış Verileri</h2>
@Html.ActionLink("Satış Ekle", "SatisEkle", null, new { @class = "btn btn-primary margintop" })
<table class="myList table table-bordered table-striped table-hover">
    <thead style="text-align:center;">
        <tr>
            <th scope="col">Ürün</th>
            <th scope="col">Personel</th>
            <th scope="col">Müşteri</th>
            <th scope="col">Fiyat</th>
            <th scope="col">Tarih & Saat</th>
        </tr>
    </thead>
    <tbody style="text-align:center;">
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.TBL_URUN.AD</td>
                <td>@item.TBL_PERSONEL.AD @item.TBL_PERSONEL.SOYAD</td>
                <td>@item.TBL_MUSTERI.AD @item.TBL_MUSTERI.SOYAD</td>
                <td>@item.FIYAT</td>
                <td>@item.TARIH</td>


            </tr>
        }
    </tbody>
</table>

MvcStokProject/Views/Satis/SatisEkle.cshtml
@model MvcStokProject.Models.Entity.TBL_SATIS

@{
    ViewBag.Title = "SatisEkle";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("SatisEkle", "Satis", FormMethod.Post))
{
    <h2 style="text-align:center; margin-top:15px;">Satış Ekleme Paneli</h2>
    <div>
        @Html.HiddenFor(x => x.ID)
        <label style="font-weight:bold;">Ürün</label>
        @Html.DropDownListFor(x => x.TBL_URUN.ID, (List<SelectListItem>)ViewBag.urunList, new { @class = "form-control" })
        <br />
        <label style="font-weight:bold;">Personel</label>
        @Html.DropDownListFor(x => x.TBL_PERSONEL.ID, (List<SelectListItem>)ViewBag.personelList, new { @class = "form-control" })
        <br />
        <label style="font-weight:bold;">Müşteri</label>
        @Html.DropDownListFor(x => x.TBL_MUSTERI.ID, (List<SelectListItem>)ViewBag.musteriList, new { @class = "form-control" })
        <br />
        <label style="font-weight:bold;">Fiyat Tutarı</label>
        @Html.TextBoxFor(x => x.FIYAT, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Satış Yap ve Kaydet</button>
    </div>

}